### ISSUE TITLE
Newer versions of MetFrag CL not working on Win 11 (Java issues)

### ISSUE THREAD

**Issue by schymane** [ipb-halle/MetFragRelaunched#153]
Hi @sneumann and @meier-rene as requested here's the post about Win 11 / MetFrag CL issues I've noticed for a while. So far, I am unable to run any MetFrag CL newer than MetFrag2.4.5-CL on Win11 with up-to-date (as far as I can tell) Java compatible with my system. 

```
PS C:\my_path\MetFrag> java -jar MetFragCommandLine-2.5.0.jar -help
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/ipbhalle/metfrag/commandline/CommandLineTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

vs

```
PS C:\my_path\MetFrag> java -jar MetFrag2.4.5-CL.jar -help
Usage: java -jar MetFragCL.jar ParameterFile='path_to_parameterfile'
                        (to execute MetFrag with a parameter file)
        or java -jar MetFragCL.jar [args...]
                        (to execute MetFrag with parameters given on command line)
```

Java is telling me this: 

![image](https://github.com/user-attachments/assets/232b19b8-8ba0-4c32-bf1e-1ff2bb7bf2b4)

I have the same issue for 2.4.8 as for 2.5.0

```
PS C:\my_path\MetFrag> java -jar MetFragCommandLine-2.4.8.jar -help
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/ipbhalle/metfrag/commandline/CommandLineTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

This happened already when my Java was freshly installed, and if I try to update again: 
 
![image](https://github.com/user-attachments/assets/06fdd1ea-baaa-48df-910b-8b37207a411c)

**Comment by sneumann** [comment]
Thx for the report. This is not so much a Windows 11 issue, but the installed JRE/JDK you have. 
We'll either try to make this work with Java8, or report the minimum requirements on the website. For reference, here are the currently supported (and end-of-life dates) versions of Java:
https://javaalmanac.io/jdk/
And while Java8 still has 2 yrs of support, we seem to have moved to at least Java11. 
Yours, Steffen

**Comment by schymane** [comment]
So how can I upgrade, if this (out of date) version is the default and "current" version for my OS? That's why, in a way, I felt it was an OS issue...

**Comment by schymane** [comment]
OK so switching to [OpenJDK11](https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-11) seems to have worked so far (thanks for the tip!) .. once I found the option to (re)set the home path so that R is also happy... (NB: this is not changed by default going through the *.msi installation but can be manually selected and/or changed post-installation). I will close this for now, thanks!

```
PS C:\my_path\MetFrag> java -jar MetFrag2.4.5-CL.jar -help
Usage: java -jar MetFragCL.jar ParameterFile='path_to_parameterfile'
                        (to execute MetFrag with a parameter file)
        or java -jar MetFragCL.jar [args...]
                        (to execute MetFrag with parameters given on command line)
PS C:\my_path\MetFrag> java -jar MetFragCommandLine-2.4.8.jar -help
Usage: java -jar MetFragCL.jar ParameterFile='path_to_parameterfile'
                        (to execute MetFrag with a parameter file)
        or java -jar MetFragCL.jar [args...]
                        (to execute MetFrag with parameters given on command line)
PS C:\my_path\MetFrag> java -jar MetFragCommandLine-2.5.0.jar -help
Usage: java -jar MetFragCL.jar ParameterFile='path_to_parameterfile'
                        (to execute MetFrag with a parameter file)
        or java -jar MetFragCL.jar [args...]
                        (to execute MetFrag with parameters given on command line)
```
