### ISSUE TITLE
Return help message when exception is thrown

### ISSUE THREAD

**Issue by rccc** [ipb-halle/MetFragRelaunched#41]
`java -jar /home/eric/dev/gains/app/bin/MetFrag2.4.5-CL.jar  app/MetFrag/1/12-154-parameters.txt
`

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 20
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at de.ipbhalle.metfraglib.parameter.Constants.getIonisationChargeByNominalMassDifference(Constants.java:302)
	at de.ipbhalle.metfraglib.parameter.SettingsChecker.checkIonModeSettings(SettingsChecker.java:154)
	at de.ipbhalle.metfraglib.parameter.SettingsChecker.check(SettingsChecker.java:15)
	at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:89)

```
This exception is not clear, cannot guess where the error come from ( csv db file, ms2Peak file, parameters file ?).

I tried this example on the web version and it return results.

**Comment by sneumann** [comment]
Hi, can you provide an example including attaching parameter files to this issue

So we can reproduce?

From the stack trace I would double check ion mode, precursor and neutral mass, but just guessing.

Yours Steffen


I blame Android for the brevity and typos

**Comment by rccc** [comment]
@sneumann : Many thanks for response.

Here are two parameters files and their results :
