### ISSUE TITLE
STDOUT while running MetFragCL

### ISSUE THREAD

**Issue by cjhjhj** [ipb-halle/MetFragRelaunched#49]
Dear authors,

MetFragCL gives STDOUT messages like
INFO  de.ipbhalle.metfraglib.database.OnlinePubChemDatabase - Fetching candidates from PubChem
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - Got 4 candidate(s)
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 30 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 50 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 80 %
INFO  de.ipbhalle.metfraglib.process.ProcessingStatus - 100 %
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - Processed 0 candidate(s)
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 4 candidate(s) were discarded before processing due to pre-filtering
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 0 candidate(s) discarded during processing due to errors
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 0 candidate(s) discarded after processing due to post-filtering
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - Stored 0 candidate(s)

Since I have to run MetFrag many times for features, the repetition of such messages is not desirable. Please let me know if there's any way to hide those STDOUT messages.
Thanks

**Comment by korseby** [comment]
Not sure if I understand completely... If you do not like the `stdout` messages, you can either remove them at all

```sh
java -jar MetFrag2.4.5-CL.jar example_parameter_file.txt 2>&1 > /dev/null
```

or you could hide informative output using

```sh
java -jar MetFrag2.4.5-CL.jar example_parameter_file.txt | grep -v INFO
```

For most people this output is very informative as it gives hints on when certain spectra are discarded depending on the settings.

For more information on the CLI please refer https://ipb-halle.github.io/MetFrag/projects/metfragcl/ .

Best, *Kristian

**Comment by cjhjhj** [comment]
Thank you for your reply. However, both options did not work in RHEL7.

**Comment by cjhjhj** [comment]
Thank you for your reply. `java -jar MetFrag2.4.5-CL.jar example_parameter.txt > /dev/null 2>&1` worked.
By the way, let me ask another question. When I ran MetFrag multiple times (actually MetFrag2.4.5-CL.jar is called multiple times in a for loop of a python script), I came across the following error randomly.
`Error: Could not open URL connection!
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pccompound&term=72.05749890897982[MIMass]:72.05894007336966[MIMass]&retmode=json&retmax=100000
java.lang.Exception
	at de.ipbhalle.metfraglib.functions.HelperFunctions.getInputStreamFromURL(HelperFunctions.java:66)
	at de.ipbhalle.metfraglib.database.OnlinePubChemDatabase.getCandidateIdentifiers(OnlinePubChemDatabase.java:83)
	at de.ipbhalle.metfraglib.database.OnlinePubChemDatabase.getCandidateIdentifiers(OnlinePubChemDatabase.java:64)
	at de.ipbhalle.metfraglib.process.CombinedMetFragProcess.retrieveCompounds(CombinedMetFragProcess.java:77)
	at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:104)
ERROR de.ipbhalle.metfrag.commandline.CommandLineTool - Error when retrieving compounds.
Exception
`
Could you please let me know why I have such errors and how I can prevent them?

**Comment by korseby** [comment]
I guess you are running MetFrag-CLI in parallel? These kinds of error messages are caused by the database (PubChem) which receives too many requests. You can prevent this by either running only one MetFRag-CLI instance at once or using a local database build. In our PhenoMeNal Galaxy-Tool and in the msPurity Galaxy tool you can choose "MetChem" as local database and run many more examples at once.

**Comment by cjhjhj** [comment]
Thank you for your quick reply.

**Comment by korseby** [comment]
Ok. I think we tackled the issue. I'm closing here now. If there's anything else, feel free to reopen it.
