### ISSUE TITLE
MetFragCL with MetFragCandidateWriter = SDF 

### ISSUE THREAD

**Issue by meier-rene** [ipb-halle/MetFragRelaunched#51]
Questions about MetFrag

Hi, I am trying to run MetFragCL using the example provided in the tutorial - except I changed one parameter (MetFragCandidateWriter = SDF). Unfortunately, its throwing the following error:

java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')
        at de.ipbhalle.metfraglib.writer.CandidateListWriterSDF.writeFile(CandidateListWriterSDF.java:144)
        at de.ipbhalle.metfraglib.writer.CandidateListWriterSDF.write(CandidateListWriterSDF.java:179)
        at de.ipbhalle.metfraglib.writer.CandidateListWriterSDF.write(CandidateListWriterSDF.java:28)
        at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:135)
ERROR de.ipbhalle.metfrag.commandline.CommandLineTool - Error: Could not write candidate file.

Can you take a look into what’s going on? Also, how would one find the structures for the annotated fragments - is that in the SDF?

Reported by Mathusan Gunabalasingam

**Comment by meier-rene** [comment]
ok, I can reproduce exactly the same error.
