### ISSUE TITLE
NPE in generateFragmentImages

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/MetFragRelaunched#84]
Hi, getting an NPE apparently while creating Fragment images
Yours, Steffen
```
Wed, Feb 23 2022 9:53:35 pm | generateFragmentImages
Wed, Feb 23 2022 9:53:35 pm | java.lang.NullPointerException
Wed, Feb 23 2022 9:53:35 pm | at java.base/java.util.Hashtable.put(Unknown Source)
Wed, Feb 23 2022 9:53:35 pm | at de.ipbhalle.metfraglib.candidate.PrecursorCandidate.<init>(PrecursorCandidate.java:34)
Wed, Feb 23 2022 9:53:35 pm | at de.ipbhalle.metfragweb.datatype.Molecule.getCandidate(Molecule.java:288)
Wed, Feb 23 2022 9:53:35 pm | at de.ipbhalle.metfragweb.controller.MetFragWebBean.generateFragmentImages(MetFragWebBean.java:2758)
Wed, Feb 23 2022 9:53:35 pm | at de.ipbhalle.metfragweb.controller.MetFragWebBean.generateFragmentsModelViewListener(MetFragWebBean.java:2731)
```

**Comment by meier-rene** [comment]
This was fixed with b006ea964ec7e49021d3d98517f2599838fb4f4b.
